image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
  only:
  - develop

docker-build:
  stage: package
  script:
  - docker build -t "$CI_REGISTRY_IMAGE":demo .
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker push "$CI_REGISTRY_IMAGE":demo
  only:
  - develop

deploy_to_google_demo:
  image: 'google/cloud-sdk:alpine'
  stage: deploy
  script:
  # Authenticate with GKE
  # - echo "$SERVICE_ACCOUNT_KEY" > key.json
  # - cat key.json
  - echo $DOCKER_SERVER
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud config set project askwinston-251209
  - gcloud config set container/cluster aw-dev
  - gcloud config set compute/zone northamerica-northeast1-c
  - gcloud container clusters get-credentials aw-dev --zone northamerica-northeast1-c
  - gcloud components install kubectl
  - kubectl delete secret keyforbackend 
  - kubectl create secret docker-registry keyforbackend --docker-server=registry.gitlab.com --docker-username=vveerasa --docker-password=Deck2021#    --docker-email=vijayram@askwinston.ca
#  - kubectl create secret docker-registry keyforbackend --docker-server="$DOCKER_SERVER" --docker-username=vveerasa --docker-password="$DOCKER_PASSWORD" --docker-email="$DOCKER_EMAIL"
  - kubectl get secret
  - kubectl delete deployment askwin-backend 
 # - kubectl delete svc askwin-service
 # - kubectl delete ingress askwin-dev
  - kubectl apply -f load-balancing/deployment-demo.yml
  only:
  - master

