image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3.6.3-jdk-11
  stage: build
  script: 
  - mvn clean 
  - mvn install
  artifacts:
    paths:
      - target/*.jar
  only:
  - develop
  - alpha
  - master

docker-build:
  stage: package
  script:
  - docker build -t "$CI_REGISTRY_IMAGE":demo .
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker push "$CI_REGISTRY_IMAGE":demo
  only:
  - develop

deploy_to_google_demo:
  image: 'google/cloud-sdk:alpine'
  stage: deploy
  script:
  # Authenticate with GKE
  # - echo "$SERVICE_ACCOUNT_KEY" > key.json
  # - cat key.json
  - echo $DOCKER_SERVER
  - gcloud auth activate-service-account --project=askwinston-251209 --key-file=key.json
  - gcloud config set project askwinston-251209
  - gcloud config set container/cluster aw-dev
  - gcloud config set compute/zone northamerica-northeast1-c
  - gcloud container clusters get-credentials aw-dev --zone northamerica-northeast1-c
  - gcloud components install kubectl
  - kubectl delete secret --ignore-not-found=true keyforbackend 
  - kubectl create secret docker-registry keyforbackend --docker-server=registry.gitlab.com --docker-username=vveerasa --docker-password=Deck2021#    --docker-email=vijayram@askwinston.ca
  # - kubectl create secret docker-registry keyforbackend --docker-server="$DOCKER_SERVER" --docker-username=vveerasa --docker-password="$DOCKER_PASSWORD" --docker-email="$DOCKER_EMAIL"
  - kubectl get secret
  - kubectl delete deployment --ignore-not-found=true askwin-backend-dev 
 # - kubectl delete svc askwin-service
 # - kubectl delete ingress askwin-dev
  - kubectl apply -f load-balancing/deployment-demo.yml
  only:
  - develop

docker-build-alpha:
  stage: package
  script:
  - docker build -t "$CI_REGISTRY_IMAGE":alpha .
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  - docker push "$CI_REGISTRY_IMAGE":alpha
  only:
  - alpha

deploy_to_google_alpha:
  image: 'google/cloud-sdk:alpine'
  stage: deploy
  script:
  - echo $DOCKER_SERVER
  - gcloud auth activate-service-account --key-file=key.json
  - gcloud config set project askwinston-251209
  - gcloud config set container/cluster aw-dev
  - gcloud config set compute/zone northamerica-northeast1-c
  - gcloud container clusters get-credentials aw-dev --zone northamerica-northeast1-c
  - gcloud components install kubectl
  - kubectl delete secret --ignore-not-found=true keyforbackendalpha 
  - kubectl create secret docker-registry keyforbackendalpha --docker-server=registry.gitlab.com --docker-username=vveerasa --docker-password=Deck2021# --docker-email=vijayram@askwinston.ca
  - kubectl get secret
  - kubectl delete deployment --ignore-not-found=true askwin-backend-alpha
  - kubectl apply -f load-balancing/deployment-alpha.yml
  only:
  - alpha

docker-build-prod:
  stage: package
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":prod .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$CI_REGISTRY_IMAGE":prod
  only:
    - master

deploy_to_google_prod:
  image: 'google/cloud-sdk:alpine'
  stage: deploy
  script:
    - echo $DOCKER_SERVER
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project askwinston-251209
    - gcloud config set container/cluster aw-prod
    - gcloud config set compute/zone northamerica-northeast1-a
    - gcloud container clusters get-credentials aw-prod --zone northamerica-northeast1-a
    - gcloud components install kubectl
    - kubectl delete secret --ignore-not-found=true keyforbackendprod
    - kubectl create secret docker-registry keyforbackendprod --docker-server=registry.gitlab.com --docker-username=vveerasa --docker-password=Deck2021# --docker-email=vijayram@askwinston.ca
    - kubectl get secret
    - kubectl delete deployment --ignore-not-found=true askwin-backend-prod
    - kubectl apply -f load-balancing/deployment-prod.yml
  only:
    - master
