apiVersion: apps/v1
kind: Deployment
metadata:
  name: aw-alpha-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: aw
  template:
    metadata:
      labels:
        application: aw
    spec:
      containers:
        - name: aw-alpha-container
          image: "gcr.io/askwinston-251209/askwinston:latest"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "demo"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 200
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
            initialDelaySeconds: 200

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: aw-alpha-backendconfig
spec:
  timeoutSec: 120

---

apiVersion: v1
kind: Service
metadata:
  name: aw-alpha-service
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"aw-alpha-backendconfig"}}'
spec:
  type: NodePort
  selector:
    application: aw
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aw-alpha-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: aw-alpha-static-ip
spec:
  backend:
    serviceName: aw-alpha-service
    servicePort: 80