apiVersion: apps/v1
kind: Deployment
metadata:
  name: aw-prod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: aw
  template:
    metadata:
      labels:
        application: aw
    spec:
      containers:
        - name: aw-prod-container
          image: "gcr.io/askwinston-251209/askwinston:master"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              httpHeaders:
            initialDelaySeconds: 20

---

apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: aw-prod-backendconfig
spec:
  timeoutSec: 120

---

apiVersion: v1
kind: Service
metadata:
  name: aw-service
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"aw-prod-backendconfig"}}'
spec:
  type: NodePort
  selector:
    application: aw
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aw-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: aw-prod-ip
    networking.gke.io/managed-certificates: "aw-prod-cert-domain-apex,aw-prod-cert-domain-www"
spec:
  backend:
    serviceName: aw-prod-service
    servicePort: 80
