apiVersion: apps/v1
kind: Deployment
metadata:
  name: askwin-backend-dev
  namespace: default
spec:
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - image: registry.gitlab.com/xyhealth/askwinston-bd:demo
        imagePullPolicy: Always
        name: askwin-backend
        args: ["--spring.profiles.active=demo"]
        livenessProbe:
          httpGet:
            path: /actuator
            port: 8081
          initialDelaySeconds: 40
          periodSeconds: 40       
      restartPolicy: Always
      imagePullSecrets:
      - name: keyfordevenv

---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: aw-dev-backendconfig
spec:
  timeoutSec: 120

---
apiVersion: v1
kind: Service
metadata:
  name: askwin-backend-dev
  namespace: default
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8081":"aw-dev-backendconfig"}}'  
  labels:
    run: backend  
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: askwin-api-ingress-dev
  labels:
    run: backend  
  annotations:
    kubernetes.io/ingress.global-static-ip-name: askwin-api-dev
spec:
  backend:
    serviceName: askwin-backend-dev
    servicePort: 8081
