apiVersion: apps/v1
kind: Deployment
metadata:
  name: askwin-backend
  namespace: default
spec:
  selector:
    matchLabels:
      application: askwin-backend
  template:
    metadata:
      labels:
        application: askwin-backend
    spec:
      containers:
      - image: registry.gitlab.com/xyhealth/askwinston-bd:demo
        imagePullPolicy: Always
        name: askwin-backend
        args: ["--spring.profiles.active=demo"]
      restartPolicy: Always
      imagePullSecrets:
      - name: keyfordevenv

---
apiVersion: v1
kind: askwin-backend-Service
metadata:
  name: askwin-backend
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: askwin-backend
  type: NodePort
