apiVersion: apps/v1
kind: Deployment
metadata:
  name: askwin-backend-alpha
  namespace: default
spec:
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - image: registry.gitlab.com/xyhealth/askwinston-bd:alpha
        imagePullPolicy: Always
        name: askwin-backend
        args: ["--spring.profiles.active=alpha"]
      restartPolicy: Always
      imagePullSecrets:
      - name: keyforbackendalpha

---
apiVersion: v1
kind: Service
metadata:
  name: askwin-backend-alpha
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: askwin-api-ingress-alpha
  labels:
    run: backend  
  annotations:
    kubernetes.io/ingress.global-static-ip-name: askwin-api-alpha
spec:
  backend:
    serviceName: askwin-backend-alpha
    servicePort: 8081

