apiVersion: apps/v1
kind: Deployment
metadata:
  name: askwin-backend-dev
  namespace: default
spec:
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - image: registry.gitlab.com/xyhealth/askwinston-bd:demo
        imagePullPolicy: Always
        name: askwin-backend
        args: ["--spring.profiles.active=demo"]
      restartPolicy: Always
      imagePullSecrets:
      - name: keyfordevenv

---
apiVersion: v1
kind: Service
metadata:
  name: askwin-backend
  namespace: default
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    run: backend
  type: NodePort
